site_name: UrbanMapper Community
repo_name: simonprovost/UrbanMapper-Community

repo_url: https://github.com/simonprovost/UrbanMapper-Community
edit_uri: blob/main/docs/
site_url: https://vida-nyu.github.io/UrbanMapper/

site_author: Simon Provost
copyright: Maintained by Simon Provost, © Simon Provost 2025-present
site_description: >
  🗺️ UrbanMapper Community: Spatially join and enrich urban layers with Scikit-Learn-like pipelines, and share insights
  with the urban research community.

remote_branch: main

theme:
  name: material
  custom_dir: docs/theme/overrides
  palette:
    - scheme: slate
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - announce.dismiss
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.top
    - search.suggest
    - toc.follow
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
  logo: public/resources/urban_mapper_logo.ico
  favicon: public/resources/urban_mapper_logo.ico

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path:
        - docs
      restrict_base_path: false
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - document-dates:
      position: bottom
      type: date
      locale: en
      date_format: '%Y-%m-%d'
      time_format: '%H:%M:%S'
      exclude:
        - index.md
        - copy_of_examples/*
      show_author: true
  - mkdocs-jupyter:
      include_source: true
      execute: true
      execute_ignore:
        - "copy_of_examples/1-Per-Module/1-loader.ipynb"
        - "copy_of_examples/1-Per-Module/2-urban_layer.ipynb"
        - "copy_of_examples/1-Per-Module/3-imputer.ipynb"
        - "copy_of_examples/1-Per-Module/4-filter.ipynb"
        - "copy_of_examples/1-Per-Module/5-enricher.ipynb"
        - "copy_of_examples/1-Per-Module/6-visualiser.ipynb"
        - "copy_of_examples/1-Per-Module/7-urban_pipeline.ipynb"
        - "copy_of_examples/1-Per-Module/8-pipeline_generator.ipynb"
        - "copy_of_examples/2-End-to-End/1-step_by_step.ipynb"
        - "copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/1-Downtown_BK_Collisions_StepByStep.ipynb"
        - "copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/2-Downtown_BK_Collisions_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/3-Downtown_BK_Collisions_Advanced_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/4-Downtown_BK_Collisions_Advanced_Pipeline_Extras.ipynb"
        - "copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/1-Downtown_BK_Taxi_Trips_StepByStep.ipynb"
        - "copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/2-Downtown_BK_Taxi_Trips_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/3-Downtown_BK_Taxi_Trips_Advanced_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/4-Downtown_BK_Taxi_Trips_Advanced_Pipeline_Extras.ipynb"
        - "copy_of_examples/3-Case-Studies/3-Europe-Restaurants/1-EU_Restaurants_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/4-Paris-Remarkable-Trees/1-Paris_Remarquable_Trees_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/4-Paris-Remarkable-Trees/2-Paris_Remarquable_Trees_Advanced_Pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/5-Overture-instead-of-OSM/1-overture_pipeline.ipynb"
        - "copy_of_examples/3-Case-Studies/5-Overture-instead-of-OSM/2-overture_pipeline_advanced.ipynb"
        - "copy_of_examples/4-External-Libraries-Usages/1-auctus_search.ipynb"
        - "copy_of_examples/4-External-Libraries-Usages/2-interactive_table_vis.ipynb"
        - "copy_of_examples/4-External-Libraries-Usages/3-jupyter_gis_multi_pipeline/1-one_pipeline.ipynb"
        - "copy_of_examples/4-External-Libraries-Usages/3-jupyter_gis_multi_pipeline/2-two_pipeline.ipynb"
        - "copy_of_examples/4-External-Libraries-Usages/3-jupyter_gis_multi_pipeline/3-three_pipeline.ipynb"

  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            heading_level: 3
            show_root_heading: true
            show_category_heading: true
            show_root_full_path: false

  - autorefs
  - privacy
  - social
  - minify
  - mermaid2

extra:
  social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/UrbanMapper-Community
      - icon: fontawesome/brands/github
        link: https://github.com/simonprovost

extra_css:
  - stylesheets/extra.css
  - stylesheets/landing.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Getting Started Step-By-Step: getting-started/quick-start_step_by_step.md
    - Getting Started W/ Pipeline: getting-started/quick-start_pipeline.md
  - Examples:
      - Overview: EXAMPLES.md
      - Per-Module Examples:
          - "Loader": copy_of_examples/1-Per-Module/1-loader.ipynb
          - "Urban Layer": copy_of_examples/1-Per-Module/2-urban_layer.ipynb
          - "Imputer": copy_of_examples/1-Per-Module/3-imputer.ipynb
          - "Filter": copy_of_examples/1-Per-Module/4-filter.ipynb
          - "Enricher": copy_of_examples/1-Per-Module/5-enricher.ipynb
          - "Visualiser": copy_of_examples/1-Per-Module/6-visualiser.ipynb
          - "Urban Pipeline": copy_of_examples/1-Per-Module/7-urban_pipeline.ipynb
          - "Pipeline Generator": copy_of_examples/1-Per-Module/8-pipeline_generator.ipynb
      - End-to-End Examples:
          - "Step by Step": copy_of_examples/2-End-to-End/1-step_by_step.ipynb
          - "Pipeline Way": copy_of_examples/2-End-to-End/2-pipeline_way.ipynb
      - Case Studies:
          - Downtown BK Collisions:
              - "Step by Step": copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/1-Downtown_BK_Collisions_StepByStep.ipynb
              - "Pipeline": copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/2-Downtown_BK_Collisions_Pipeline.ipynb
              - "Advanced Pipeline": copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/3-Downtown_BK_Collisions_Advanced_Pipeline.ipynb
              - "Advanced Pipeline Extras": copy_of_examples/3-Case-Studies/1-Downtown-BK-Collisions/4-Downtown_BK_Collisions_Advanced_Pipeline_Extras.ipynb
          - Downtown BK Taxi Trips:
              - "Step by Step": copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/1-Downtown_BK_Taxi_Trips_StepByStep.ipynb
              - "Pipeline": copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/2-Downtown_BK_Taxi_Trips_Pipeline.ipynb
              - "Advanced Pipeline": copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/3-Downtown_BK_Taxi_Trips_Advanced_Pipeline.ipynb
              - "Advanced Pipeline Extras": copy_of_examples/3-Case-Studies/2-Downtown-BK-Taxi-Trips/4-Downtown_BK_Taxi_Trips_Advanced_Pipeline_Extras.ipynb
          - Europe Restaurants:
              - "EU Restaurants Pipeline": copy_of_examples/3-Case-Studies/3-Europe-Restaurants/1-EU_Restaurants_Pipeline.ipynb
          - Paris Remarkable Trees:
              - "Pipeline": copy_of_examples/3-Case-Studies/4-Paris-Remarkable-Trees/1-Paris_Remarquable_Trees_Pipeline.ipynb
              - "Advanced Pipeline": copy_of_examples/3-Case-Studies/4-Paris-Remarkable-Trees/2-Paris_Remarquable_Trees_Advanced_Pipeline.ipynb
          - Overture instead of OSM:
              - "Overture Pipeline": copy_of_examples/3-Case-Studies/5-Overture-instead-of-OSM/1-overture_pipeline.ipynb
              - "Advanced Overture Pipeline": copy_of_examples/3-Case-Studies/5-Overture-instead-of-OSM/2-overture_pipeline_advanced.ipynb
      - External Libraries Usages:
          - "Auctus Search": copy_of_examples/4-External-Libraries-Usages/1-auctus_search.ipynb
          - "Interactive Table VIS": copy_of_examples/4-External-Libraries-Usages/2-interactive_table_vis.ipynb
          - "Jupyter GIS Multi Pipeline":
              - One Pipeline: copy_of_examples/4-External-Libraries-Usages/3-jupyter_gis_multi_pipeline/1-one_pipeline.ipynb
              - Two Pipeline: copy_of_examples/4-External-Libraries-Usages/3-jupyter_gis_multi_pipeline/2-two_pipeline.ipynb
              - Three Pipeline: copy_of_examples/4-External-Libraries-Usages/3-jupyter_gis_multi_pipeline/3-three_pipeline.ipynb
  - API:
      - Overview: api/index.md
      - Loaders: api/loaders.md
      - Urban Layers: api/urban_layers.md
      - Imputers: api/imputers.md
      - Filters: api/filters.md
      - Enrichers: api/enrichers.md
      - Visualisers: api/visualisers.md
      - Pipelines: api/pipelines.md
      - Pipeline Generators: api/pipeline_generators.md
      - Auctus Mixins: api/auctus.md
      - Interactive Table VIS: api/interactive_table_vis.md
      - JupyterGIS Mixins: api/jupyter_gis.md
  - Community Hub:
      - Overview: community-hub.md
      - Our Story: community-story.md
      - Contributing: CONTRIBUTING_DEV.md
      - Branding & UX: BRANDING.md
